
#define  CXPATHJSON_OK 0
#define  CXPATHJSON_DOCUMENT_NOT_EXIST_CODE 1
#define  CXPATHJSON_DOCUMENT_NOT_PARSABLE_CODE 2
#define  CXPATHJSON_ARG_PATH_NOT_VALID_CODE 3
#define  CXPATHJSON_ELEMENT_PATH_NOT_EXIST_CODE 4
#define  CXPATHJSON_MIDDLE_ELEMENT_ITS_NOT_OBJECT 5
#define  CXPATHJSON_MIDDLE_ELEMENT_ITS_NOT_ITERABLE 6
#define  CXPATHJSON_MIDDLE_ELEMENT_ITS_NOT_ARRAY 7
#define  CXPATHJSON_ELEMENT_HAS_WRONG_TYPE 8
#define  CXPATHJSON_PRINT_PROBLEM 9
#define  CXPATHJSON_IO_PROBLEM 10
#define CJSON_PATH_APPEND_ITS_NOT_VALID_ON_READ_OPERATIONS 11


void newCxpathJson_raise_errror(CxpathJson * self, int error_code, const char *path, const char *format, ...);


void newCxpathJson_clear_errors(CxpathJson * self);