
#define  CJSON_PATH_DOCUMENT_NOT_EXIST_CODE 1
#define  CJSON_PATH_DOCUMENT_NOT_PARSABLE_CODE 2
#define  CJSON_PATH_ARG_PATH_NOT_VALID_CODE 3
#define  CJSON_PATH_ELEMENT_PATH_NOT_EXIST_CODE 4

#define  CJSON_PATH_ELEMENT_HAS_WRONG_TYPE 5
